language: android
android:
  components:
    - build-tools-28.0.3
jdk: oraclejdk8
before_install:
 - git clone --depth=50 https://github.com/wala/WALA WALA
install:
 - pushd WALA
 - mvn clean install -DskipTests -B -q
 - popd
script:
 - make test
sudo: false
cache:
  directories:
    - $HOME/.m2
